name: Publish API Documentation

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      working-directory: ./src/DeckSurf.SDK
      run: dotnet build --configuration Release
    - name: Test
      working-directory: ./src/DeckSurf.SDK
      run: dotnet test --configuration Release --no-build
    - name: Download mdoc
      run: Invoke-WebRequest https://github.com/mono/api-doc-tools/releases/download/mdoc-5.8.3/mdoc-5.8.3.zip -OutFile mdoc.zip
    - name: Extract mdoc
      run: Expand-Archive -Path mdoc.zip -DestinationPath _mdoc
    - name: List folder contents
      run: ls
    - name: List mdoc folder contents
      run: ls _mdoc
    - name: List _mdoc from inside binary folder
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: ls ${env:GITHUB_WORKSPACE}\_mdoc
    - name: Run mdoc bootstrap
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: $env:GITHUB_WORKSPACE\_mdoc\mdoc.exe fx-bootstrap
    - name: List generated content
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: ls
