name: Publish API Documentation

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      working-directory: ./src/DeckSurf.SDK
      run: dotnet build --configuration Release
    - name: Test
      working-directory: ./src/DeckSurf.SDK
      run: dotnet test --configuration Release --no-build
    - name: Download mdoc
      run: Invoke-WebRequest https://github.com/mono/api-doc-tools/releases/download/mdoc-5.8.3/mdoc-5.8.3.zip -OutFile mdoc.zip
    - name: Download ECMA2YAML
      run: Invoke-WebRequest https://www.nuget.org/api/v2/package/Microsoft.DocAsCode.ECMA2Yaml/1.0.916 -OutFile ecma2yaml.zip
    - name: Extract mdoc
      run: Expand-Archive -Path mdoc.zip -DestinationPath _mdoc
    - name: Extract ECMA2YAML
      run: Expand-Archive -Path ecma2yaml.zip -DestinationPath _ecma2yaml
    - name: List folder contents
      run: ls
    - name: List mdoc folder contents
      run: ls _mdoc
    - name: List _mdoc from inside binary folder
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: ls ${env:GITHUB_WORKSPACE}\_mdoc
    - name: Run mdoc bootstrap
      working-directory: ./src/DeckSurf.SDK/bin
      run: ${{ github.workspace }}\_mdoc\mdoc.exe fx-bootstrap Release
    - name: List generated content
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: ls
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: dend/decksurf-docs
        path: _docs
    - name: Run import script
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: ${{ github.workspace }}\_docs\scripts\mdoc-import.ps1
    - name: List data
      run: ls ${{ github.workspace }}
    - name: List binary data
      run: ls ${{ github.workspace }}\src\DeckSurf.SDK\bin\Release\net5.0
    - name: Show file contents
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: cat frameworks.xml
    - name: Run XML generation
      working-directory: ./src/DeckSurf.SDK/bin/Release
      run: ${{ github.workspace }}\_mdoc\mdoc.exe update --debug --out _xml -fx (Resolve-Path frameworks.xml) --use-docid
    - name: Run YAML generation
      run: _ecma2yaml\tools\ecma2yaml.exe update -s ${{ github.workspace }}\src\DeckSurf.SDK\bin\Release\_xml -o _ready_yaml
